# Generated by Django 4.0.4 on 2022-05-31 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='name',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='message',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
